Develop
SlavaAndreievvvv/Cryptoriance pull request #1
Opened 2023-01-04 11:55 UTC by SlavaAndreievvvv

2023-01-04 12:02 UTC, SlavaAndreievvvv commented
Кудись стрілочки пропали, спробую виправити до того як ти перевіриш.

2023-01-10 12:55 UTC, a1exalexander requested changes
![image](https://user-images.githubusercontent.com/40409129/211555752-5be2e0c5-badc-443e-b440-b8948422cde5.png)

- [ ] 1 -  если это возможно, саму линию нужно растянуть на всю ширину экрана
- [ ] 2 - все карточки на большом экране должны быть  по центру, для красоты как минимум

![image](https://user-images.githubusercontent.com/40409129/211556476-d5f0723a-fc2f-4d72-a3d2-12b5c07bad02.png)

- [ ] расстояние между табами и полосой внизу должно быть больше
![image](https://user-images.githubusercontent.com/40409129/211556739-5a00be7c-c081-409a-83e1-805d7ceb846d.png)

![image](https://user-images.githubusercontent.com/40409129/211556908-35e8ce93-f821-434c-abd5-9b13068bf806.png)

- [ ] так же нужно центрировать на больших мониках

![image](https://user-images.githubusercontent.com/40409129/211557010-9b0244d9-e892-4c9d-b447-725c2e803480.png)

- [ ] картинка растянута! искажена!

2023-01-10 12:55 UTC, a1exalexander commented on src/scss/components/_burger.scss
> +}
```suggestion
  &__item,
  &::after,
  &::before {
    display: block;
    height: 2px;
    width: 100%;
    background-color: utils.$color-grey-2;
    border-radius: 2px;
  }
  &::after,
  &::before {
    content: "";
    transition: transform .7s ease, width .5s ease .2s;
  }
}
```

2023-01-10 12:55 UTC, a1exalexander commented on src/scss/components/_circle.scss
> +  }
Такие модификаторы плохая практика делать! Если это порядковый номер, то делай через `nth`

2023-01-10 12:55 UTC, a1exalexander commented on src/scss/components/_circle.scss
> +  }
⬆️ такая же ситуация

2023-01-10 12:55 UTC, a1exalexander commented on src/scss/components/_circle.scss
> +  }
⬆️ такая же фигня

2023-01-10 12:55 UTC, a1exalexander commented on src/scss/components/_crypto-block.scss
> +  &-1 {
что это за - черточка? 
есть блок `.crypto-block`
есть елементы блока `.crypto-block__title`
могут быть модификаторы блока или елемента `.crypto-block--dark` `.crypto-block__title--small`

это я для примера написал!!!

`.crypto-block-1` такого синтаксиса нету

эти стили должны применяться для каждого из этих блоков отдельно! в отдельных файлах, но те стили которые влияют на внешнее расположение доложны находится в файле 
`features-section.scss` как модификаторы для `features-section__crypto-block`

2023-01-20 14:52 UTC, a1exalexander requested changes
Останній ривок!

2023-01-20 14:52 UTC, a1exalexander commented
![image](https://user-images.githubusercontent.com/40409129/213728156-663848b5-1303-4e55-9904-a74c87eeae36.png)

при наведенні щось не то робиться

2023-01-20 14:53 UTC, a1exalexander commented
![image](https://user-images.githubusercontent.com/40409129/213728336-90c807e1-37ab-4e7c-936e-384b2f8d0a3d.png)
 Додай курсор `pointer` і якийсь ефект при наведенні на свій розсуд

2023-01-20 14:55 UTC, a1exalexander commented
![image](https://user-images.githubusercontent.com/40409129/213728614-90cd8bca-d028-4d91-b9e5-1a769a51c6f3.png)

Додай якийсь ефект при наведженні на свій смак + додай href="#" хоча б, бо не зрозуміло чи то лінк взагалі! І зроби так для усіх тегів `<a>`

2023-01-20 14:57 UTC, a1exalexander commented
![image](https://user-images.githubusercontent.com/40409129/213729155-03589a48-a0da-4a72-89d8-884fa86cc1fb.png)

На кнопках відсутній `hover`  стилі

2023-01-20 14:59 UTC, a1exalexander commented
![image](https://user-images.githubusercontent.com/40409129/213729533-59c5d4ac-be44-419e-afca-46c335cc01bf.png)

курсов `pointer` і `hover` якийсь треба

2023-01-30 15:07 UTC, a1exalexander requested changes
- [x] Дуже довгі анімації( Треба чекати пока з'явиться щось, зроби набагато швидше

2023-01-30 15:09 UTC, a1exalexander commented
![image](https://user-images.githubusercontent.com/40409129/215514793-099f047c-c7d7-4fb9-bad2-81b33ab1e3f6.png)

в тебе тут зайвий відступ від сірої полоски то синьої полоски

2023-01-30 15:15 UTC, SlavaAndreievvvv commented
Сорі, виправлю!

2023-02-15 16:57 UTC, a1exalexander approved these changes

2023-02-15 16:57 UTC, merged